apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-docker-k8s
spec:
  selector:
    matchLabels:
      app: react-docker-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: react-docker-k8s
    spec:
     containers:
     - name: react-docker-k8s
       image: dash1007/reactimage
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: react-docker-k8s
  namespace: default
spec:
  type: NodePort
  selector:
    app: react-docker-k8s
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
